# The following is automatically generated by code_factory.py

from numba import njit


@njit
def xs(index, reaction, data):
    offset = reaction["xs_offset"]
    return data[offset + index]


@njit
def xs_all(reaction, data):
    start = reaction["xs_offset"]
    size = reaction["xs_length"]
    end = start + size
    return data[start:end]


@njit
def xs_last(reaction, data):
    start = reaction["xs_offset"]
    size = reaction["xs_length"]
    end = start + size
    return data[end - 1]


@njit
def xs_chunk(start, length, reaction, data):
    start += reaction["xs_offset"]
    end = start + length
    return data[start:end]
