# The following is automatically generated by code_factory.py

from numba import njit


@njit
def x(index, table_data, data):
    offset = table_data["x_offset"]
    return data[offset + index]


@njit
def x_all(table_data, data):
    start = table_data["x_offset"]
    size = table_data["x_length"]
    end = start + size
    return data[start:end]


@njit
def x_last(table_data, data):
    start = table_data["x_offset"]
    size = table_data["x_length"]
    end = start + size
    return data[end - 1]


@njit
def x_chunk(start, length, table_data, data):
    start += table_data["x_offset"]
    end = start + length
    return data[start:end]


@njit
def y(index, table_data, data):
    offset = table_data["y_offset"]
    return data[offset + index]


@njit
def y_all(table_data, data):
    start = table_data["y_offset"]
    size = table_data["y_length"]
    end = start + size
    return data[start:end]


@njit
def y_last(table_data, data):
    start = table_data["y_offset"]
    size = table_data["y_length"]
    end = start + size
    return data[end - 1]


@njit
def y_chunk(start, length, table_data, data):
    start += table_data["y_offset"]
    end = start + length
    return data[start:end]
