# The following is automatically generated by code_factory.py

from numba import njit


@njit
def binding_energy(index, electron_ionization_reaction, data):
    offset = electron_ionization_reaction["binding_energy_offset"]
    return data[offset + index]


@njit
def binding_energy_all(electron_ionization_reaction, data):
    start = electron_ionization_reaction["binding_energy_offset"]
    size = electron_ionization_reaction["binding_energy_length"]
    end = start + size
    return data[start:end]


@njit
def binding_energy_last(electron_ionization_reaction, data):
    start = electron_ionization_reaction["binding_energy_offset"]
    size = electron_ionization_reaction["binding_energy_length"]
    end = start + size
    return data[end - 1]


@njit
def binding_energy_chunk(start, length, electron_ionization_reaction, data):
    start += electron_ionization_reaction["binding_energy_offset"]
    end = start + length
    return data[start:end]
