# The following is automatically generated by code_factory.py

from numpy import int64
from numba import njit


from mcdc.code_factory.array_return import array_return, array_result


import numba as nb


@njit
def electron_xs_energy_grid(index, element, data):
    offset = element["electron_xs_energy_grid_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def electron_xs_energy_grid_all(element, data):
    start = element["electron_xs_energy_grid_offset"]
    size = element["electron_xs_energy_grid_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def electron_xs_energy_grid_last(element, data):
    start = element["electron_xs_energy_grid_offset"]
    size = element["electron_xs_energy_grid_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def electron_xs_energy_grid_chunk(start, length, element, data):
    start += element["electron_xs_energy_grid_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def electron_total_xs(index, element, data):
    offset = element["electron_total_xs_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def electron_total_xs_all(element, data):
    start = element["electron_total_xs_offset"]
    size = element["electron_total_xs_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def electron_total_xs_last(element, data):
    start = element["electron_total_xs_offset"]
    size = element["electron_total_xs_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def electron_total_xs_chunk(start, length, element, data):
    start += element["electron_total_xs_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def electron_ionization_xs(index, element, data):
    offset = element["electron_ionization_xs_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def electron_ionization_xs_all(element, data):
    start = element["electron_ionization_xs_offset"]
    size = element["electron_ionization_xs_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def electron_ionization_xs_last(element, data):
    start = element["electron_ionization_xs_offset"]
    size = element["electron_ionization_xs_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def electron_ionization_xs_chunk(start, length, element, data):
    start += element["electron_ionization_xs_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def electron_elastic_xs(index, element, data):
    offset = element["electron_elastic_xs_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def electron_elastic_xs_all(element, data):
    start = element["electron_elastic_xs_offset"]
    size = element["electron_elastic_xs_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def electron_elastic_xs_last(element, data):
    start = element["electron_elastic_xs_offset"]
    size = element["electron_elastic_xs_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def electron_elastic_xs_chunk(start, length, element, data):
    start += element["electron_elastic_xs_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def electron_excitation_xs(index, element, data):
    offset = element["electron_excitation_xs_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def electron_excitation_xs_all(element, data):
    start = element["electron_excitation_xs_offset"]
    size = element["electron_excitation_xs_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def electron_excitation_xs_last(element, data):
    start = element["electron_excitation_xs_offset"]
    size = element["electron_excitation_xs_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def electron_excitation_xs_chunk(start, length, element, data):
    start += element["electron_excitation_xs_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def electron_bremsstrahlung_xs(index, element, data):
    offset = element["electron_bremsstrahlung_xs_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def electron_bremsstrahlung_xs_all(element, data):
    start = element["electron_bremsstrahlung_xs_offset"]
    size = element["electron_bremsstrahlung_xs_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def electron_bremsstrahlung_xs_last(element, data):
    start = element["electron_bremsstrahlung_xs_offset"]
    size = element["electron_bremsstrahlung_xs_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def electron_bremsstrahlung_xs_chunk(start, length, element, data):
    start += element["electron_bremsstrahlung_xs_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def electron_ionization_reaction_IDs(index, element, data):
    offset = element["electron_ionization_reaction_IDs_offset"]
    return int64(data[offset + index])


@array_return(nb.types.float64)
def electron_ionization_reaction_IDs_all(element, data):
    start = element["electron_ionization_reaction_IDs_offset"]
    size = element["N_electron_ionization_reaction"]
    end = start + size
    return array_result(data[start:end])


@njit
def electron_ionization_reaction_IDs_last(element, data):
    start = element["electron_ionization_reaction_IDs_offset"]
    size = element["N_electron_ionization_reaction"]
    end = start + size
    return int64(data[end - 1])


@array_return(nb.types.float64)
def electron_ionization_reaction_IDs_chunk(start, length, element, data):
    start += element["electron_ionization_reaction_IDs_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def electron_elastic_scattering_reaction_IDs(index, element, data):
    offset = element["electron_elastic_scattering_reaction_IDs_offset"]
    return int64(data[offset + index])


@array_return(nb.types.float64)
def electron_elastic_scattering_reaction_IDs_all(element, data):
    start = element["electron_elastic_scattering_reaction_IDs_offset"]
    size = element["N_electron_elastic_scattering_reaction"]
    end = start + size
    return array_result(data[start:end])


@njit
def electron_elastic_scattering_reaction_IDs_last(element, data):
    start = element["electron_elastic_scattering_reaction_IDs_offset"]
    size = element["N_electron_elastic_scattering_reaction"]
    end = start + size
    return int64(data[end - 1])


@array_return(nb.types.float64)
def electron_elastic_scattering_reaction_IDs_chunk(start, length, element, data):
    start += element["electron_elastic_scattering_reaction_IDs_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def electron_excitation_reaction_IDs(index, element, data):
    offset = element["electron_excitation_reaction_IDs_offset"]
    return int64(data[offset + index])


@array_return(nb.types.float64)
def electron_excitation_reaction_IDs_all(element, data):
    start = element["electron_excitation_reaction_IDs_offset"]
    size = element["N_electron_excitation_reaction"]
    end = start + size
    return array_result(data[start:end])


@njit
def electron_excitation_reaction_IDs_last(element, data):
    start = element["electron_excitation_reaction_IDs_offset"]
    size = element["N_electron_excitation_reaction"]
    end = start + size
    return int64(data[end - 1])


@array_return(nb.types.float64)
def electron_excitation_reaction_IDs_chunk(start, length, element, data):
    start += element["electron_excitation_reaction_IDs_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def electron_bremsstrahlung_reaction_IDs(index, element, data):
    offset = element["electron_bremsstrahlung_reaction_IDs_offset"]
    return int64(data[offset + index])


@array_return(nb.types.float64)
def electron_bremsstrahlung_reaction_IDs_all(element, data):
    start = element["electron_bremsstrahlung_reaction_IDs_offset"]
    size = element["N_electron_bremsstrahlung_reaction"]
    end = start + size
    return array_result(data[start:end])


@njit
def electron_bremsstrahlung_reaction_IDs_last(element, data):
    start = element["electron_bremsstrahlung_reaction_IDs_offset"]
    size = element["N_electron_bremsstrahlung_reaction"]
    end = start + size
    return int64(data[end - 1])


@array_return(nb.types.float64)
def electron_bremsstrahlung_reaction_IDs_chunk(start, length, element, data):
    start += element["electron_bremsstrahlung_reaction_IDs_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def electron_ionization_subshell_binding_energy(index, element, data):
    offset = element["electron_ionization_subshell_binding_energy_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def electron_ionization_subshell_binding_energy_all(element, data):
    start = element["electron_ionization_subshell_binding_energy_offset"]
    size = element["electron_ionization_subshell_binding_energy_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def electron_ionization_subshell_binding_energy_last(element, data):
    start = element["electron_ionization_subshell_binding_energy_offset"]
    size = element["electron_ionization_subshell_binding_energy_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def electron_ionization_subshell_binding_energy_chunk(start, length, element, data):
    start += element["electron_ionization_subshell_binding_energy_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def photon_xs_energy_grid(index, element, data):
    offset = element["photon_xs_energy_grid_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def photon_xs_energy_grid_all(element, data):
    start = element["photon_xs_energy_grid_offset"]
    size = element["photon_xs_energy_grid_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def photon_xs_energy_grid_last(element, data):
    start = element["photon_xs_energy_grid_offset"]
    size = element["photon_xs_energy_grid_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def photon_xs_energy_grid_chunk(start, length, element, data):
    start += element["photon_xs_energy_grid_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def photon_total_xs(index, element, data):
    offset = element["photon_total_xs_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def photon_total_xs_all(element, data):
    start = element["photon_total_xs_offset"]
    size = element["photon_total_xs_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def photon_total_xs_last(element, data):
    start = element["photon_total_xs_offset"]
    size = element["photon_total_xs_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def photon_total_xs_chunk(start, length, element, data):
    start += element["photon_total_xs_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def photon_coherent_xs(index, element, data):
    offset = element["photon_coherent_xs_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def photon_coherent_xs_all(element, data):
    start = element["photon_coherent_xs_offset"]
    size = element["photon_coherent_xs_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def photon_coherent_xs_last(element, data):
    start = element["photon_coherent_xs_offset"]
    size = element["photon_coherent_xs_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def photon_coherent_xs_chunk(start, length, element, data):
    start += element["photon_coherent_xs_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def photon_incoherent_xs(index, element, data):
    offset = element["photon_incoherent_xs_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def photon_incoherent_xs_all(element, data):
    start = element["photon_incoherent_xs_offset"]
    size = element["photon_incoherent_xs_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def photon_incoherent_xs_last(element, data):
    start = element["photon_incoherent_xs_offset"]
    size = element["photon_incoherent_xs_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def photon_incoherent_xs_chunk(start, length, element, data):
    start += element["photon_incoherent_xs_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def photon_photoelectric_xs(index, element, data):
    offset = element["photon_photoelectric_xs_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def photon_photoelectric_xs_all(element, data):
    start = element["photon_photoelectric_xs_offset"]
    size = element["photon_photoelectric_xs_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def photon_photoelectric_xs_last(element, data):
    start = element["photon_photoelectric_xs_offset"]
    size = element["photon_photoelectric_xs_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def photon_photoelectric_xs_chunk(start, length, element, data):
    start += element["photon_photoelectric_xs_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def photon_pair_production_xs(index, element, data):
    offset = element["photon_pair_production_xs_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def photon_pair_production_xs_all(element, data):
    start = element["photon_pair_production_xs_offset"]
    size = element["photon_pair_production_xs_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def photon_pair_production_xs_last(element, data):
    start = element["photon_pair_production_xs_offset"]
    size = element["photon_pair_production_xs_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def photon_pair_production_xs_chunk(start, length, element, data):
    start += element["photon_pair_production_xs_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def photon_coherent_reaction_IDs(index, element, data):
    offset = element["photon_coherent_reaction_IDs_offset"]
    return int64(data[offset + index])


@array_return(nb.types.float64)
def photon_coherent_reaction_IDs_all(element, data):
    start = element["photon_coherent_reaction_IDs_offset"]
    size = element["N_photon_coherent_reaction"]
    end = start + size
    return array_result(data[start:end])


@njit
def photon_coherent_reaction_IDs_last(element, data):
    start = element["photon_coherent_reaction_IDs_offset"]
    size = element["N_photon_coherent_reaction"]
    end = start + size
    return int64(data[end - 1])


@array_return(nb.types.float64)
def photon_coherent_reaction_IDs_chunk(start, length, element, data):
    start += element["photon_coherent_reaction_IDs_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def photon_incoherent_reaction_IDs(index, element, data):
    offset = element["photon_incoherent_reaction_IDs_offset"]
    return int64(data[offset + index])


@array_return(nb.types.float64)
def photon_incoherent_reaction_IDs_all(element, data):
    start = element["photon_incoherent_reaction_IDs_offset"]
    size = element["N_photon_incoherent_reaction"]
    end = start + size
    return array_result(data[start:end])


@njit
def photon_incoherent_reaction_IDs_last(element, data):
    start = element["photon_incoherent_reaction_IDs_offset"]
    size = element["N_photon_incoherent_reaction"]
    end = start + size
    return int64(data[end - 1])


@array_return(nb.types.float64)
def photon_incoherent_reaction_IDs_chunk(start, length, element, data):
    start += element["photon_incoherent_reaction_IDs_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def photon_photoelectric_reaction_IDs(index, element, data):
    offset = element["photon_photoelectric_reaction_IDs_offset"]
    return int64(data[offset + index])


@array_return(nb.types.float64)
def photon_photoelectric_reaction_IDs_all(element, data):
    start = element["photon_photoelectric_reaction_IDs_offset"]
    size = element["N_photon_photoelectric_reaction"]
    end = start + size
    return array_result(data[start:end])


@njit
def photon_photoelectric_reaction_IDs_last(element, data):
    start = element["photon_photoelectric_reaction_IDs_offset"]
    size = element["N_photon_photoelectric_reaction"]
    end = start + size
    return int64(data[end - 1])


@array_return(nb.types.float64)
def photon_photoelectric_reaction_IDs_chunk(start, length, element, data):
    start += element["photon_photoelectric_reaction_IDs_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def photon_pair_production_reaction_IDs(index, element, data):
    offset = element["photon_pair_production_reaction_IDs_offset"]
    return int64(data[offset + index])


@array_return(nb.types.float64)
def photon_pair_production_reaction_IDs_all(element, data):
    start = element["photon_pair_production_reaction_IDs_offset"]
    size = element["N_photon_pair_production_reaction"]
    end = start + size
    return array_result(data[start:end])


@njit
def photon_pair_production_reaction_IDs_last(element, data):
    start = element["photon_pair_production_reaction_IDs_offset"]
    size = element["N_photon_pair_production_reaction"]
    end = start + size
    return int64(data[end - 1])


@array_return(nb.types.float64)
def photon_pair_production_reaction_IDs_chunk(start, length, element, data):
    start += element["photon_pair_production_reaction_IDs_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def photon_photoelectric_subshell_binding_energy(index, element, data):
    offset = element["photon_photoelectric_subshell_binding_energy_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def photon_photoelectric_subshell_binding_energy_all(element, data):
    start = element["photon_photoelectric_subshell_binding_energy_offset"]
    size = element["photon_photoelectric_subshell_binding_energy_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def photon_photoelectric_subshell_binding_energy_last(element, data):
    start = element["photon_photoelectric_subshell_binding_energy_offset"]
    size = element["photon_photoelectric_subshell_binding_energy_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def photon_photoelectric_subshell_binding_energy_chunk(start, length, element, data):
    start += element["photon_photoelectric_subshell_binding_energy_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def photon_relaxation_transition_energy(index, element, data):
    offset = element["photon_relaxation_transition_energy_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def photon_relaxation_transition_energy_all(element, data):
    start = element["photon_relaxation_transition_energy_offset"]
    size = element["photon_relaxation_transition_energy_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def photon_relaxation_transition_energy_last(element, data):
    start = element["photon_relaxation_transition_energy_offset"]
    size = element["photon_relaxation_transition_energy_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def photon_relaxation_transition_energy_chunk(start, length, element, data):
    start += element["photon_relaxation_transition_energy_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def photon_relaxation_transition_probability(index, element, data):
    offset = element["photon_relaxation_transition_probability_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def photon_relaxation_transition_probability_all(element, data):
    start = element["photon_relaxation_transition_probability_offset"]
    size = element["photon_relaxation_transition_probability_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def photon_relaxation_transition_probability_last(element, data):
    start = element["photon_relaxation_transition_probability_offset"]
    size = element["photon_relaxation_transition_probability_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def photon_relaxation_transition_probability_chunk(start, length, element, data):
    start += element["photon_relaxation_transition_probability_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def photon_relaxation_transition_radiative(index, element, data):
    offset = element["photon_relaxation_transition_radiative_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def photon_relaxation_transition_radiative_all(element, data):
    start = element["photon_relaxation_transition_radiative_offset"]
    size = element["photon_relaxation_transition_radiative_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def photon_relaxation_transition_radiative_last(element, data):
    start = element["photon_relaxation_transition_radiative_offset"]
    size = element["photon_relaxation_transition_radiative_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def photon_relaxation_transition_radiative_chunk(start, length, element, data):
    start += element["photon_relaxation_transition_radiative_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def photon_relaxation_transition_origin(index, element, data):
    offset = element["photon_relaxation_transition_origin_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def photon_relaxation_transition_origin_all(element, data):
    start = element["photon_relaxation_transition_origin_offset"]
    size = element["photon_relaxation_transition_origin_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def photon_relaxation_transition_origin_last(element, data):
    start = element["photon_relaxation_transition_origin_offset"]
    size = element["photon_relaxation_transition_origin_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def photon_relaxation_transition_origin_chunk(start, length, element, data):
    start += element["photon_relaxation_transition_origin_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def photon_relaxation_subshell_start(index, element, data):
    offset = element["photon_relaxation_subshell_start_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def photon_relaxation_subshell_start_all(element, data):
    start = element["photon_relaxation_subshell_start_offset"]
    size = element["photon_relaxation_subshell_start_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def photon_relaxation_subshell_start_last(element, data):
    start = element["photon_relaxation_subshell_start_offset"]
    size = element["photon_relaxation_subshell_start_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def photon_relaxation_subshell_start_chunk(start, length, element, data):
    start += element["photon_relaxation_subshell_start_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def photon_relaxation_subshell_count(index, element, data):
    offset = element["photon_relaxation_subshell_count_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def photon_relaxation_subshell_count_all(element, data):
    start = element["photon_relaxation_subshell_count_offset"]
    size = element["photon_relaxation_subshell_count_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def photon_relaxation_subshell_count_last(element, data):
    start = element["photon_relaxation_subshell_count_offset"]
    size = element["photon_relaxation_subshell_count_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def photon_relaxation_subshell_count_chunk(start, length, element, data):
    start += element["photon_relaxation_subshell_count_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def photon_relaxation_subshell_designator(index, element, data):
    offset = element["photon_relaxation_subshell_designator_offset"]
    return data[offset + index]


@array_return(nb.types.float64)
def photon_relaxation_subshell_designator_all(element, data):
    start = element["photon_relaxation_subshell_designator_offset"]
    size = element["photon_relaxation_subshell_designator_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def photon_relaxation_subshell_designator_last(element, data):
    start = element["photon_relaxation_subshell_designator_offset"]
    size = element["photon_relaxation_subshell_designator_length"]
    end = start + size
    return data[end - 1]


@array_return(nb.types.float64)
def photon_relaxation_subshell_designator_chunk(start, length, element, data):
    start += element["photon_relaxation_subshell_designator_offset"]
    end = start + length
    return array_result(data[start:end])
