# The following is automatically generated by code_factory.py

from numba import njit


@njit
def cell_IDs(index, forced_collisions, data):
    offset = forced_collisions["cell_IDs_offset"]
    return data[offset + index]


@njit
def cell_IDs_all(forced_collisions, data):
    start = forced_collisions["cell_IDs_offset"]
    size = forced_collisions["cell_IDs_length"]
    end = start + size
    return data[start:end]


@njit
def cell_IDs_last(forced_collisions, data):
    start = forced_collisions["cell_IDs_offset"]
    size = forced_collisions["cell_IDs_length"]
    end = start + size
    return data[end - 1]


@njit
def cell_IDs_chunk(start, length, forced_collisions, data):
    start += forced_collisions["cell_IDs_offset"]
    end = start + length
    return data[start:end]


@njit
def threshold_weights(index, forced_collisions, data):
    offset = forced_collisions["threshold_weights_offset"]
    return data[offset + index]


@njit
def threshold_weights_all(forced_collisions, data):
    start = forced_collisions["threshold_weights_offset"]
    size = forced_collisions["threshold_weights_length"]
    end = start + size
    return data[start:end]


@njit
def threshold_weights_last(forced_collisions, data):
    start = forced_collisions["threshold_weights_offset"]
    size = forced_collisions["threshold_weights_length"]
    end = start + size
    return data[end - 1]


@njit
def threshold_weights_chunk(start, length, forced_collisions, data):
    start += forced_collisions["threshold_weights_offset"]
    end = start + length
    return data[start:end]


@njit
def target_weights(index, forced_collisions, data):
    offset = forced_collisions["target_weights_offset"]
    return data[offset + index]


@njit
def target_weights_all(forced_collisions, data):
    start = forced_collisions["target_weights_offset"]
    size = forced_collisions["target_weights_length"]
    end = start + size
    return data[start:end]


@njit
def target_weights_last(forced_collisions, data):
    start = forced_collisions["target_weights_offset"]
    size = forced_collisions["target_weights_length"]
    end = start + size
    return data[end - 1]


@njit
def target_weights_chunk(start, length, forced_collisions, data):
    start += forced_collisions["target_weights_offset"]
    end = start + length
    return data[start:end]
