# The following is automatically generated by code_factory.py

from numba import njit


@njit
def xs_energy_grid(index, nuclide, data):
    offset = nuclide["xs_energy_grid_offset"]
    return data[offset + index]


@njit
def xs_energy_grid_all(nuclide, data):
    start = nuclide["xs_energy_grid_offset"]
    size = nuclide["xs_energy_grid_length"]
    end = start + size
    return data[start:end]


@njit
def xs_energy_grid_last(nuclide, data):
    start = nuclide["xs_energy_grid_offset"]
    size = nuclide["xs_energy_grid_length"]
    end = start + size
    return data[end - 1]


@njit
def xs_energy_grid_chunk(start, length, nuclide, data):
    start += nuclide["xs_energy_grid_offset"]
    end = start + length
    return data[start:end]


@njit
def total_xs(index, nuclide, data):
    offset = nuclide["total_xs_offset"]
    return data[offset + index]


@njit
def total_xs_all(nuclide, data):
    start = nuclide["total_xs_offset"]
    size = nuclide["total_xs_length"]
    end = start + size
    return data[start:end]


@njit
def total_xs_last(nuclide, data):
    start = nuclide["total_xs_offset"]
    size = nuclide["total_xs_length"]
    end = start + size
    return data[end - 1]


@njit
def total_xs_chunk(start, length, nuclide, data):
    start += nuclide["total_xs_offset"]
    end = start + length
    return data[start:end]


@njit
def elastic_xs(index, nuclide, data):
    offset = nuclide["elastic_xs_offset"]
    return data[offset + index]


@njit
def elastic_xs_all(nuclide, data):
    start = nuclide["elastic_xs_offset"]
    size = nuclide["elastic_xs_length"]
    end = start + size
    return data[start:end]


@njit
def elastic_xs_last(nuclide, data):
    start = nuclide["elastic_xs_offset"]
    size = nuclide["elastic_xs_length"]
    end = start + size
    return data[end - 1]


@njit
def elastic_xs_chunk(start, length, nuclide, data):
    start += nuclide["elastic_xs_offset"]
    end = start + length
    return data[start:end]


@njit
def capture_xs(index, nuclide, data):
    offset = nuclide["capture_xs_offset"]
    return data[offset + index]


@njit
def capture_xs_all(nuclide, data):
    start = nuclide["capture_xs_offset"]
    size = nuclide["capture_xs_length"]
    end = start + size
    return data[start:end]


@njit
def capture_xs_last(nuclide, data):
    start = nuclide["capture_xs_offset"]
    size = nuclide["capture_xs_length"]
    end = start + size
    return data[end - 1]


@njit
def capture_xs_chunk(start, length, nuclide, data):
    start += nuclide["capture_xs_offset"]
    end = start + length
    return data[start:end]


@njit
def inelastic_xs(index, nuclide, data):
    offset = nuclide["inelastic_xs_offset"]
    return data[offset + index]


@njit
def inelastic_xs_all(nuclide, data):
    start = nuclide["inelastic_xs_offset"]
    size = nuclide["inelastic_xs_length"]
    end = start + size
    return data[start:end]


@njit
def inelastic_xs_last(nuclide, data):
    start = nuclide["inelastic_xs_offset"]
    size = nuclide["inelastic_xs_length"]
    end = start + size
    return data[end - 1]


@njit
def inelastic_xs_chunk(start, length, nuclide, data):
    start += nuclide["inelastic_xs_offset"]
    end = start + length
    return data[start:end]


@njit
def fission_xs(index, nuclide, data):
    offset = nuclide["fission_xs_offset"]
    return data[offset + index]


@njit
def fission_xs_all(nuclide, data):
    start = nuclide["fission_xs_offset"]
    size = nuclide["fission_xs_length"]
    end = start + size
    return data[start:end]


@njit
def fission_xs_last(nuclide, data):
    start = nuclide["fission_xs_offset"]
    size = nuclide["fission_xs_length"]
    end = start + size
    return data[end - 1]


@njit
def fission_xs_chunk(start, length, nuclide, data):
    start += nuclide["fission_xs_offset"]
    end = start + length
    return data[start:end]


@njit
def elastic_scattering_reaction_IDs(index, nuclide, data):
    offset = nuclide["elastic_scattering_reaction_IDs_offset"]
    return data[offset + index]


@njit
def elastic_scattering_reaction_IDs_all(nuclide, data):
    start = nuclide["elastic_scattering_reaction_IDs_offset"]
    size = nuclide["N_elastic_scattering_reaction"]
    end = start + size
    return data[start:end]


@njit
def elastic_scattering_reaction_IDs_last(nuclide, data):
    start = nuclide["elastic_scattering_reaction_IDs_offset"]
    size = nuclide["N_elastic_scattering_reaction"]
    end = start + size
    return data[end - 1]


@njit
def elastic_scattering_reaction_IDs_chunk(start, length, nuclide, data):
    start += nuclide["elastic_scattering_reaction_IDs_offset"]
    end = start + length
    return data[start:end]


@njit
def capture_reaction_IDs(index, nuclide, data):
    offset = nuclide["capture_reaction_IDs_offset"]
    return data[offset + index]


@njit
def capture_reaction_IDs_all(nuclide, data):
    start = nuclide["capture_reaction_IDs_offset"]
    size = nuclide["N_capture_reaction"]
    end = start + size
    return data[start:end]


@njit
def capture_reaction_IDs_last(nuclide, data):
    start = nuclide["capture_reaction_IDs_offset"]
    size = nuclide["N_capture_reaction"]
    end = start + size
    return data[end - 1]


@njit
def capture_reaction_IDs_chunk(start, length, nuclide, data):
    start += nuclide["capture_reaction_IDs_offset"]
    end = start + length
    return data[start:end]


@njit
def inelastic_scattering_reaction_IDs(index, nuclide, data):
    offset = nuclide["inelastic_scattering_reaction_IDs_offset"]
    return data[offset + index]


@njit
def inelastic_scattering_reaction_IDs_all(nuclide, data):
    start = nuclide["inelastic_scattering_reaction_IDs_offset"]
    size = nuclide["N_inelastic_scattering_reaction"]
    end = start + size
    return data[start:end]


@njit
def inelastic_scattering_reaction_IDs_last(nuclide, data):
    start = nuclide["inelastic_scattering_reaction_IDs_offset"]
    size = nuclide["N_inelastic_scattering_reaction"]
    end = start + size
    return data[end - 1]


@njit
def inelastic_scattering_reaction_IDs_chunk(start, length, nuclide, data):
    start += nuclide["inelastic_scattering_reaction_IDs_offset"]
    end = start + length
    return data[start:end]


@njit
def fission_reaction_IDs(index, nuclide, data):
    offset = nuclide["fission_reaction_IDs_offset"]
    return data[offset + index]


@njit
def fission_reaction_IDs_all(nuclide, data):
    start = nuclide["fission_reaction_IDs_offset"]
    size = nuclide["N_fission_reaction"]
    end = start + size
    return data[start:end]


@njit
def fission_reaction_IDs_last(nuclide, data):
    start = nuclide["fission_reaction_IDs_offset"]
    size = nuclide["N_fission_reaction"]
    end = start + size
    return data[end - 1]


@njit
def fission_reaction_IDs_chunk(start, length, nuclide, data):
    start += nuclide["fission_reaction_IDs_offset"]
    end = start + length
    return data[start:end]


@njit
def fission_delayed_fractions(index, nuclide, data):
    offset = nuclide["fission_delayed_fractions_offset"]
    return data[offset + index]


@njit
def fission_delayed_fractions_all(nuclide, data):
    start = nuclide["fission_delayed_fractions_offset"]
    size = nuclide["fission_delayed_fractions_length"]
    end = start + size
    return data[start:end]


@njit
def fission_delayed_fractions_last(nuclide, data):
    start = nuclide["fission_delayed_fractions_offset"]
    size = nuclide["fission_delayed_fractions_length"]
    end = start + size
    return data[end - 1]


@njit
def fission_delayed_fractions_chunk(start, length, nuclide, data):
    start += nuclide["fission_delayed_fractions_offset"]
    end = start + length
    return data[start:end]


@njit
def fission_delayed_decay_rates(index, nuclide, data):
    offset = nuclide["fission_delayed_decay_rates_offset"]
    return data[offset + index]


@njit
def fission_delayed_decay_rates_all(nuclide, data):
    start = nuclide["fission_delayed_decay_rates_offset"]
    size = nuclide["fission_delayed_decay_rates_length"]
    end = start + size
    return data[start:end]


@njit
def fission_delayed_decay_rates_last(nuclide, data):
    start = nuclide["fission_delayed_decay_rates_offset"]
    size = nuclide["fission_delayed_decay_rates_length"]
    end = start + size
    return data[end - 1]


@njit
def fission_delayed_decay_rates_chunk(start, length, nuclide, data):
    start += nuclide["fission_delayed_decay_rates_offset"]
    end = start + length
    return data[start:end]


@njit
def fission_delayed_spectrum_IDs(index, nuclide, data):
    offset = nuclide["fission_delayed_spectrum_IDs_offset"]
    return data[offset + index]


@njit
def fission_delayed_spectrum_IDs_all(nuclide, data):
    start = nuclide["fission_delayed_spectrum_IDs_offset"]
    size = nuclide["N_fission_delayed_spectrum"]
    end = start + size
    return data[start:end]


@njit
def fission_delayed_spectrum_IDs_last(nuclide, data):
    start = nuclide["fission_delayed_spectrum_IDs_offset"]
    size = nuclide["N_fission_delayed_spectrum"]
    end = start + size
    return data[end - 1]


@njit
def fission_delayed_spectrum_IDs_chunk(start, length, nuclide, data):
    start += nuclide["fission_delayed_spectrum_IDs_offset"]
    end = start + length
    return data[start:end]
