# The following is automatically generated by code_factory.py

from numpy import int64
from numba import njit


from mcdc.code_factory.array_return import array_return, array_result


import numba as nb


@njit
def subshell_x_IDs(index, photon_photoelectric_reaction, data):
    offset = photon_photoelectric_reaction["subshell_x_IDs_offset"]
    return int64(data[offset + index])


@array_return(nb.types.float64)
def subshell_x_IDs_all(photon_photoelectric_reaction, data):
    start = photon_photoelectric_reaction["subshell_x_IDs_offset"]
    size = photon_photoelectric_reaction["N_subshell_x"]
    end = start + size
    return array_result(data[start:end])


@njit
def subshell_x_IDs_last(photon_photoelectric_reaction, data):
    start = photon_photoelectric_reaction["subshell_x_IDs_offset"]
    size = photon_photoelectric_reaction["N_subshell_x"]
    end = start + size
    return int64(data[end - 1])


@array_return(nb.types.float64)
def subshell_x_IDs_chunk(start, length, photon_photoelectric_reaction, data):
    start += photon_photoelectric_reaction["subshell_x_IDs_offset"]
    end = start + length
    return array_result(data[start:end])
