# The following is automatically generated by code_factory.py

from numba import njit


@njit
def coefficients(index, polynomial_data, data):
    offset = polynomial_data["coefficients_offset"]
    return data[offset + index]


@njit
def coefficients_all(polynomial_data, data):
    start = polynomial_data["coefficients_offset"]
    size = polynomial_data["coefficients_length"]
    end = start + size
    return data[start:end]


@njit
def coefficients_last(polynomial_data, data):
    start = polynomial_data["coefficients_offset"]
    size = polynomial_data["coefficients_length"]
    end = start + size
    return data[end - 1]


@njit
def coefficients_chunk(start, length, polynomial_data, data):
    start += polynomial_data["coefficients_offset"]
    end = start + length
    return data[start:end]
