# The following is automatically generated by code_factory.py

from numba import njit


@njit
def spectrum_probability_grid(index, proton_nonelastic_reaction, data):
    offset = proton_nonelastic_reaction["spectrum_probability_grid_offset"]
    return data[offset + index]


@njit
def spectrum_probability_grid_all(proton_nonelastic_reaction, data):
    start = proton_nonelastic_reaction["spectrum_probability_grid_offset"]
    size = proton_nonelastic_reaction["spectrum_probability_grid_length"]
    end = start + size
    return data[start:end]


@njit
def spectrum_probability_grid_last(proton_nonelastic_reaction, data):
    start = proton_nonelastic_reaction["spectrum_probability_grid_offset"]
    size = proton_nonelastic_reaction["spectrum_probability_grid_length"]
    end = start + size
    return data[end - 1]


@njit
def spectrum_probability_grid_chunk(start, length, proton_nonelastic_reaction, data):
    start += proton_nonelastic_reaction["spectrum_probability_grid_offset"]
    end = start + length
    return data[start:end]


@njit
def spectrum_probability_vector(index_1, proton_nonelastic_reaction, data):
    offset = proton_nonelastic_reaction["spectrum_probability_offset"]
    stride = proton_nonelastic_reaction["N_spectrum"]
    start = offset + index_1 * stride
    end = start + stride
    return data[start:end]


@njit
def spectrum_probability(index_1, index_2, proton_nonelastic_reaction, data):
    offset = proton_nonelastic_reaction["spectrum_probability_offset"]
    stride = proton_nonelastic_reaction["N_spectrum"]
    return data[offset + index_1 * stride + index_2]


@njit
def spectrum_probability_chunk(start, length, proton_nonelastic_reaction, data):
    start += proton_nonelastic_reaction["spectrum_probability_offset"]
    end = start + length
    return data[start:end]


@njit
def energy_spectrum_IDs(index, proton_nonelastic_reaction, data):
    offset = proton_nonelastic_reaction["energy_spectrum_IDs_offset"]
    return data[offset + index]


@njit
def energy_spectrum_IDs_all(proton_nonelastic_reaction, data):
    start = proton_nonelastic_reaction["energy_spectrum_IDs_offset"]
    size = proton_nonelastic_reaction["N_energy_spectrum"]
    end = start + size
    return data[start:end]


@njit
def energy_spectrum_IDs_last(proton_nonelastic_reaction, data):
    start = proton_nonelastic_reaction["energy_spectrum_IDs_offset"]
    size = proton_nonelastic_reaction["N_energy_spectrum"]
    end = start + size
    return data[end - 1]


@njit
def energy_spectrum_IDs_chunk(start, length, proton_nonelastic_reaction, data):
    start += proton_nonelastic_reaction["energy_spectrum_IDs_offset"]
    end = start + length
    return data[start:end]
