# The following is automatically generated by code_factory.py

from numba import njit


@njit
def xs(index, proton_reaction, data):
    offset = proton_reaction["xs_offset"]
    return data[offset + index]


@njit
def xs_all(proton_reaction, data):
    start = proton_reaction["xs_offset"]
    size = proton_reaction["xs_length"]
    end = start + size
    return data[start:end]


@njit
def xs_last(proton_reaction, data):
    start = proton_reaction["xs_offset"]
    size = proton_reaction["xs_length"]
    end = start + size
    return data[end - 1]


@njit
def xs_chunk(start, length, proton_reaction, data):
    start += proton_reaction["xs_offset"]
    end = start + length
    return data[start:end]
