# The following is automatically generated by code_factory.py

from numba import njit


@njit
def k_cycle(index, simulation, data):
    offset = simulation["k_cycle_offset"]
    return data[offset + index]


@njit
def k_cycle_all(simulation, data):
    start = simulation["k_cycle_offset"]
    size = simulation["k_cycle_length"]
    end = start + size
    return data[start:end]


@njit
def k_cycle_last(simulation, data):
    start = simulation["k_cycle_offset"]
    size = simulation["k_cycle_length"]
    end = start + size
    return data[end - 1]


@njit
def k_cycle_chunk(start, length, simulation, data):
    start += simulation["k_cycle_offset"]
    end = start + length
    return data[start:end]


@njit
def gyration_radius(index, simulation, data):
    offset = simulation["gyration_radius_offset"]
    return data[offset + index]


@njit
def gyration_radius_all(simulation, data):
    start = simulation["gyration_radius_offset"]
    size = simulation["gyration_radius_length"]
    end = start + size
    return data[start:end]


@njit
def gyration_radius_last(simulation, data):
    start = simulation["gyration_radius_offset"]
    size = simulation["gyration_radius_length"]
    end = start + size
    return data[end - 1]


@njit
def gyration_radius_chunk(start, length, simulation, data):
    start += simulation["gyration_radius_offset"]
    end = start + length
    return data[start:end]
