# The following is automatically generated by code_factory.py

from numba import njit


@njit
def cdf(index, tabulated_distribution, data):
    offset = tabulated_distribution["cdf_offset"]
    return data[offset + index]


@njit
def cdf_all(tabulated_distribution, data):
    start = tabulated_distribution["cdf_offset"]
    size = tabulated_distribution["cdf_length"]
    end = start + size
    return data[start:end]


@njit
def cdf_last(tabulated_distribution, data):
    start = tabulated_distribution["cdf_offset"]
    size = tabulated_distribution["cdf_length"]
    end = start + size
    return data[end - 1]


@njit
def cdf_chunk(start, length, tabulated_distribution, data):
    start += tabulated_distribution["cdf_offset"]
    end = start + length
    return data[start:end]
