# The following is automatically generated by code_factory.py

from numpy import int64
from numba import njit


from mcdc.code_factory.array_return import array_return, array_result


import numba as nb


@njit
def weight_window_types(index, technique, data):
    offset = technique["weight_window_types_offset"]
    return int64(data[offset + index])


@array_return(nb.types.float64)
def weight_window_types_all(technique, data):
    start = technique["weight_window_types_offset"]
    size = technique["weight_window_types_length"]
    end = start + size
    return array_result(data[start:end])


@njit
def weight_window_types_last(technique, data):
    start = technique["weight_window_types_offset"]
    size = technique["weight_window_types_length"]
    end = start + size
    return int64(data[end - 1])


@array_return(nb.types.float64)
def weight_window_types_chunk(start, length, technique, data):
    start += technique["weight_window_types_offset"]
    end = start + length
    return array_result(data[start:end])


@njit
def weight_window_IDs(index, technique, data):
    offset = technique["weight_window_IDs_offset"]
    return int64(data[offset + index])


@array_return(nb.types.float64)
def weight_window_IDs_all(technique, data):
    start = technique["weight_window_IDs_offset"]
    size = technique["N_weight_window"]
    end = start + size
    return array_result(data[start:end])


@njit
def weight_window_IDs_last(technique, data):
    start = technique["weight_window_IDs_offset"]
    size = technique["N_weight_window"]
    end = start + size
    return int64(data[end - 1])


@array_return(nb.types.float64)
def weight_window_IDs_chunk(start, length, technique, data):
    start += technique["weight_window_IDs_offset"]
    end = start + length
    return array_result(data[start:end])
