# The following is automatically generated by code_factory.py

from numba import njit


@njit
def weight_windows(index, weight_windows, data):
    offset = weight_windows["weight_windows_offset"]
    return data[offset + index]


@njit
def weight_windows_all(weight_windows, data):
    start = weight_windows["weight_windows_offset"]
    size = weight_windows["weight_windows_length"]
    end = start + size
    return data[start:end]


@njit
def weight_windows_last(weight_windows, data):
    start = weight_windows["weight_windows_offset"]
    size = weight_windows["weight_windows_length"]
    end = start + size
    return data[end - 1]


@njit
def weight_windows_chunk(start, length, weight_windows, data):
    start += weight_windows["weight_windows_offset"]
    end = start + length
    return data[start:end]
