# The following is automatically generated by code_factory.py

from numba import njit


@njit
def energy(index, kalbach_mann_distribution, data, value):
    offset = kalbach_mann_distribution["energy_offset"]
    data[offset + index] = value


@njit
def energy_all(kalbach_mann_distribution, data, value):
    start = kalbach_mann_distribution["energy_offset"]
    size = kalbach_mann_distribution["energy_length"]
    end = start + size
    data[start:end] = value


@njit
def energy_last(kalbach_mann_distribution, data, value):
    start = kalbach_mann_distribution["energy_offset"]
    size = kalbach_mann_distribution["energy_length"]
    end = start + size
    data[end - 1] = value


@njit
def energy_chunk(start, length, kalbach_mann_distribution, data, value):
    start += kalbach_mann_distribution["energy_offset"]
    end = start + length
    data[start:end] = value


@njit
def offset(index, kalbach_mann_distribution, data, value):
    offset = kalbach_mann_distribution["offset_offset"]
    data[offset + index] = value


@njit
def offset_all(kalbach_mann_distribution, data, value):
    start = kalbach_mann_distribution["offset_offset"]
    size = kalbach_mann_distribution["offset_length"]
    end = start + size
    data[start:end] = value


@njit
def offset_last(kalbach_mann_distribution, data, value):
    start = kalbach_mann_distribution["offset_offset"]
    size = kalbach_mann_distribution["offset_length"]
    end = start + size
    data[end - 1] = value


@njit
def offset_chunk(start, length, kalbach_mann_distribution, data, value):
    start += kalbach_mann_distribution["offset_offset"]
    end = start + length
    data[start:end] = value


@njit
def energy_out(index, kalbach_mann_distribution, data, value):
    offset = kalbach_mann_distribution["energy_out_offset"]
    data[offset + index] = value


@njit
def energy_out_all(kalbach_mann_distribution, data, value):
    start = kalbach_mann_distribution["energy_out_offset"]
    size = kalbach_mann_distribution["energy_out_length"]
    end = start + size
    data[start:end] = value


@njit
def energy_out_last(kalbach_mann_distribution, data, value):
    start = kalbach_mann_distribution["energy_out_offset"]
    size = kalbach_mann_distribution["energy_out_length"]
    end = start + size
    data[end - 1] = value


@njit
def energy_out_chunk(start, length, kalbach_mann_distribution, data, value):
    start += kalbach_mann_distribution["energy_out_offset"]
    end = start + length
    data[start:end] = value


@njit
def pdf(index, kalbach_mann_distribution, data, value):
    offset = kalbach_mann_distribution["pdf_offset"]
    data[offset + index] = value


@njit
def pdf_all(kalbach_mann_distribution, data, value):
    start = kalbach_mann_distribution["pdf_offset"]
    size = kalbach_mann_distribution["pdf_length"]
    end = start + size
    data[start:end] = value


@njit
def pdf_last(kalbach_mann_distribution, data, value):
    start = kalbach_mann_distribution["pdf_offset"]
    size = kalbach_mann_distribution["pdf_length"]
    end = start + size
    data[end - 1] = value


@njit
def pdf_chunk(start, length, kalbach_mann_distribution, data, value):
    start += kalbach_mann_distribution["pdf_offset"]
    end = start + length
    data[start:end] = value


@njit
def cdf(index, kalbach_mann_distribution, data, value):
    offset = kalbach_mann_distribution["cdf_offset"]
    data[offset + index] = value


@njit
def cdf_all(kalbach_mann_distribution, data, value):
    start = kalbach_mann_distribution["cdf_offset"]
    size = kalbach_mann_distribution["cdf_length"]
    end = start + size
    data[start:end] = value


@njit
def cdf_last(kalbach_mann_distribution, data, value):
    start = kalbach_mann_distribution["cdf_offset"]
    size = kalbach_mann_distribution["cdf_length"]
    end = start + size
    data[end - 1] = value


@njit
def cdf_chunk(start, length, kalbach_mann_distribution, data, value):
    start += kalbach_mann_distribution["cdf_offset"]
    end = start + length
    data[start:end] = value


@njit
def precompound_factor(index, kalbach_mann_distribution, data, value):
    offset = kalbach_mann_distribution["precompound_factor_offset"]
    data[offset + index] = value


@njit
def precompound_factor_all(kalbach_mann_distribution, data, value):
    start = kalbach_mann_distribution["precompound_factor_offset"]
    size = kalbach_mann_distribution["precompound_factor_length"]
    end = start + size
    data[start:end] = value


@njit
def precompound_factor_last(kalbach_mann_distribution, data, value):
    start = kalbach_mann_distribution["precompound_factor_offset"]
    size = kalbach_mann_distribution["precompound_factor_length"]
    end = start + size
    data[end - 1] = value


@njit
def precompound_factor_chunk(start, length, kalbach_mann_distribution, data, value):
    start += kalbach_mann_distribution["precompound_factor_offset"]
    end = start + length
    data[start:end] = value


@njit
def angular_slope(index, kalbach_mann_distribution, data, value):
    offset = kalbach_mann_distribution["angular_slope_offset"]
    data[offset + index] = value


@njit
def angular_slope_all(kalbach_mann_distribution, data, value):
    start = kalbach_mann_distribution["angular_slope_offset"]
    size = kalbach_mann_distribution["angular_slope_length"]
    end = start + size
    data[start:end] = value


@njit
def angular_slope_last(kalbach_mann_distribution, data, value):
    start = kalbach_mann_distribution["angular_slope_offset"]
    size = kalbach_mann_distribution["angular_slope_length"]
    end = start + size
    data[end - 1] = value


@njit
def angular_slope_chunk(start, length, kalbach_mann_distribution, data, value):
    start += kalbach_mann_distribution["angular_slope_offset"]
    end = start + length
    data[start:end] = value
