# The following is automatically generated by code_factory.py

from numba import njit


@njit
def value(index, pmf_distribution, data, value):
    offset = pmf_distribution["value_offset"]
    data[offset + index] = value


@njit
def value_all(pmf_distribution, data, value):
    start = pmf_distribution["value_offset"]
    size = pmf_distribution["value_length"]
    end = start + size
    data[start:end] = value


@njit
def value_last(pmf_distribution, data, value):
    start = pmf_distribution["value_offset"]
    size = pmf_distribution["value_length"]
    end = start + size
    data[end - 1] = value


@njit
def value_chunk(start, length, pmf_distribution, data, value):
    start += pmf_distribution["value_offset"]
    end = start + length
    data[start:end] = value


@njit
def pmf(index, pmf_distribution, data, value):
    offset = pmf_distribution["pmf_offset"]
    data[offset + index] = value


@njit
def pmf_all(pmf_distribution, data, value):
    start = pmf_distribution["pmf_offset"]
    size = pmf_distribution["pmf_length"]
    end = start + size
    data[start:end] = value


@njit
def pmf_last(pmf_distribution, data, value):
    start = pmf_distribution["pmf_offset"]
    size = pmf_distribution["pmf_length"]
    end = start + size
    data[end - 1] = value


@njit
def pmf_chunk(start, length, pmf_distribution, data, value):
    start += pmf_distribution["pmf_offset"]
    end = start + length
    data[start:end] = value


@njit
def cmf(index, pmf_distribution, data, value):
    offset = pmf_distribution["cmf_offset"]
    data[offset + index] = value


@njit
def cmf_all(pmf_distribution, data, value):
    start = pmf_distribution["cmf_offset"]
    size = pmf_distribution["cmf_length"]
    end = start + size
    data[start:end] = value


@njit
def cmf_last(pmf_distribution, data, value):
    start = pmf_distribution["cmf_offset"]
    size = pmf_distribution["cmf_length"]
    end = start + size
    data[end - 1] = value


@njit
def cmf_chunk(start, length, pmf_distribution, data, value):
    start += pmf_distribution["cmf_offset"]
    end = start + length
    data[start:end] = value
