# The following is automatically generated by code_factory.py

from numba import njit


@njit
def xs(index, reaction, data, value):
    offset = reaction["xs_offset"]
    data[offset + index] = value


@njit
def xs_all(reaction, data, value):
    start = reaction["xs_offset"]
    size = reaction["xs_length"]
    end = start + size
    data[start:end] = value


@njit
def xs_last(reaction, data, value):
    start = reaction["xs_offset"]
    size = reaction["xs_length"]
    end = start + size
    data[end - 1] = value


@njit
def xs_chunk(start, length, reaction, data, value):
    start += reaction["xs_offset"]
    end = start + length
    data[start:end] = value
