# The following is automatically generated by code_factory.py

from numba import njit


@njit
def k_cycle(index, simulation, data, value):
    offset = simulation["k_cycle_offset"]
    data[offset + index] = value


@njit
def k_cycle_all(simulation, data, value):
    start = simulation["k_cycle_offset"]
    size = simulation["k_cycle_length"]
    end = start + size
    data[start:end] = value


@njit
def k_cycle_last(simulation, data, value):
    start = simulation["k_cycle_offset"]
    size = simulation["k_cycle_length"]
    end = start + size
    data[end - 1] = value


@njit
def k_cycle_chunk(start, length, simulation, data, value):
    start += simulation["k_cycle_offset"]
    end = start + length
    data[start:end] = value


@njit
def gyration_radius(index, simulation, data, value):
    offset = simulation["gyration_radius_offset"]
    data[offset + index] = value


@njit
def gyration_radius_all(simulation, data, value):
    start = simulation["gyration_radius_offset"]
    size = simulation["gyration_radius_length"]
    end = start + size
    data[start:end] = value


@njit
def gyration_radius_last(simulation, data, value):
    start = simulation["gyration_radius_offset"]
    size = simulation["gyration_radius_length"]
    end = start + size
    data[end - 1] = value


@njit
def gyration_radius_chunk(start, length, simulation, data, value):
    start += simulation["gyration_radius_offset"]
    end = start + length
    data[start:end] = value
