# The following is automatically generated by code_factory.py

from numba import njit


@njit
def binding_energy(index, electron_ionization_reaction, data, value):
    offset = electron_ionization_reaction["binding_energy_offset"]
    data[offset + index] = value


@njit
def binding_energy_all(electron_ionization_reaction, data, value):
    start = electron_ionization_reaction["binding_energy_offset"]
    size = electron_ionization_reaction["binding_energy_length"]
    end = start + size
    data[start:end] = value


@njit
def binding_energy_last(electron_ionization_reaction, data, value):
    start = electron_ionization_reaction["binding_energy_offset"]
    size = electron_ionization_reaction["binding_energy_length"]
    end = start + size
    data[end - 1] = value


@njit
def binding_energy_chunk(start, length, electron_ionization_reaction, data, value):
    start += electron_ionization_reaction["binding_energy_offset"]
    end = start + length
    data[start:end] = value
