# The following is automatically generated by code_factory.py

from numba import njit


@njit
def xs_energy_grid(index, element, data, value):
    offset = element["xs_energy_grid_offset"]
    data[offset + index] = value


@njit
def xs_energy_grid_all(element, data, value):
    start = element["xs_energy_grid_offset"]
    size = element["xs_energy_grid_length"]
    end = start + size
    data[start:end] = value


@njit
def xs_energy_grid_last(element, data, value):
    start = element["xs_energy_grid_offset"]
    size = element["xs_energy_grid_length"]
    end = start + size
    data[end - 1] = value


@njit
def xs_energy_grid_chunk(start, length, element, data, value):
    start += element["xs_energy_grid_offset"]
    end = start + length
    data[start:end] = value


@njit
def total_xs(index, element, data, value):
    offset = element["total_xs_offset"]
    data[offset + index] = value


@njit
def total_xs_all(element, data, value):
    start = element["total_xs_offset"]
    size = element["total_xs_length"]
    end = start + size
    data[start:end] = value


@njit
def total_xs_last(element, data, value):
    start = element["total_xs_offset"]
    size = element["total_xs_length"]
    end = start + size
    data[end - 1] = value


@njit
def total_xs_chunk(start, length, element, data, value):
    start += element["total_xs_offset"]
    end = start + length
    data[start:end] = value


@njit
def ionization_xs(index, element, data, value):
    offset = element["ionization_xs_offset"]
    data[offset + index] = value


@njit
def ionization_xs_all(element, data, value):
    start = element["ionization_xs_offset"]
    size = element["ionization_xs_length"]
    end = start + size
    data[start:end] = value


@njit
def ionization_xs_last(element, data, value):
    start = element["ionization_xs_offset"]
    size = element["ionization_xs_length"]
    end = start + size
    data[end - 1] = value


@njit
def ionization_xs_chunk(start, length, element, data, value):
    start += element["ionization_xs_offset"]
    end = start + length
    data[start:end] = value


@njit
def elastic_xs(index, element, data, value):
    offset = element["elastic_xs_offset"]
    data[offset + index] = value


@njit
def elastic_xs_all(element, data, value):
    start = element["elastic_xs_offset"]
    size = element["elastic_xs_length"]
    end = start + size
    data[start:end] = value


@njit
def elastic_xs_last(element, data, value):
    start = element["elastic_xs_offset"]
    size = element["elastic_xs_length"]
    end = start + size
    data[end - 1] = value


@njit
def elastic_xs_chunk(start, length, element, data, value):
    start += element["elastic_xs_offset"]
    end = start + length
    data[start:end] = value


@njit
def excitation_xs(index, element, data, value):
    offset = element["excitation_xs_offset"]
    data[offset + index] = value


@njit
def excitation_xs_all(element, data, value):
    start = element["excitation_xs_offset"]
    size = element["excitation_xs_length"]
    end = start + size
    data[start:end] = value


@njit
def excitation_xs_last(element, data, value):
    start = element["excitation_xs_offset"]
    size = element["excitation_xs_length"]
    end = start + size
    data[end - 1] = value


@njit
def excitation_xs_chunk(start, length, element, data, value):
    start += element["excitation_xs_offset"]
    end = start + length
    data[start:end] = value


@njit
def bremsstrahlung_xs(index, element, data, value):
    offset = element["bremsstrahlung_xs_offset"]
    data[offset + index] = value


@njit
def bremsstrahlung_xs_all(element, data, value):
    start = element["bremsstrahlung_xs_offset"]
    size = element["bremsstrahlung_xs_length"]
    end = start + size
    data[start:end] = value


@njit
def bremsstrahlung_xs_last(element, data, value):
    start = element["bremsstrahlung_xs_offset"]
    size = element["bremsstrahlung_xs_length"]
    end = start + size
    data[end - 1] = value


@njit
def bremsstrahlung_xs_chunk(start, length, element, data, value):
    start += element["bremsstrahlung_xs_offset"]
    end = start + length
    data[start:end] = value


@njit
def ionization_reaction_IDs(index, element, data, value):
    offset = element["ionization_reaction_IDs_offset"]
    data[offset + index] = value


@njit
def ionization_reaction_IDs_all(element, data, value):
    start = element["ionization_reaction_IDs_offset"]
    size = element["N_ionization_reaction"]
    end = start + size
    data[start:end] = value


@njit
def ionization_reaction_IDs_last(element, data, value):
    start = element["ionization_reaction_IDs_offset"]
    size = element["N_ionization_reaction"]
    end = start + size
    data[end - 1] = value


@njit
def ionization_reaction_IDs_chunk(start, length, element, data, value):
    start += element["ionization_reaction_IDs_offset"]
    end = start + length
    data[start:end] = value


@njit
def elastic_scattering_reaction_IDs(index, element, data, value):
    offset = element["elastic_scattering_reaction_IDs_offset"]
    data[offset + index] = value


@njit
def elastic_scattering_reaction_IDs_all(element, data, value):
    start = element["elastic_scattering_reaction_IDs_offset"]
    size = element["N_elastic_scattering_reaction"]
    end = start + size
    data[start:end] = value


@njit
def elastic_scattering_reaction_IDs_last(element, data, value):
    start = element["elastic_scattering_reaction_IDs_offset"]
    size = element["N_elastic_scattering_reaction"]
    end = start + size
    data[end - 1] = value


@njit
def elastic_scattering_reaction_IDs_chunk(start, length, element, data, value):
    start += element["elastic_scattering_reaction_IDs_offset"]
    end = start + length
    data[start:end] = value


@njit
def excitation_reaction_IDs(index, element, data, value):
    offset = element["excitation_reaction_IDs_offset"]
    data[offset + index] = value


@njit
def excitation_reaction_IDs_all(element, data, value):
    start = element["excitation_reaction_IDs_offset"]
    size = element["N_excitation_reaction"]
    end = start + size
    data[start:end] = value


@njit
def excitation_reaction_IDs_last(element, data, value):
    start = element["excitation_reaction_IDs_offset"]
    size = element["N_excitation_reaction"]
    end = start + size
    data[end - 1] = value


@njit
def excitation_reaction_IDs_chunk(start, length, element, data, value):
    start += element["excitation_reaction_IDs_offset"]
    end = start + length
    data[start:end] = value


@njit
def bremsstrahlung_reaction_IDs(index, element, data, value):
    offset = element["bremsstrahlung_reaction_IDs_offset"]
    data[offset + index] = value


@njit
def bremsstrahlung_reaction_IDs_all(element, data, value):
    start = element["bremsstrahlung_reaction_IDs_offset"]
    size = element["N_bremsstrahlung_reaction"]
    end = start + size
    data[start:end] = value


@njit
def bremsstrahlung_reaction_IDs_last(element, data, value):
    start = element["bremsstrahlung_reaction_IDs_offset"]
    size = element["N_bremsstrahlung_reaction"]
    end = start + size
    data[end - 1] = value


@njit
def bremsstrahlung_reaction_IDs_chunk(start, length, element, data, value):
    start += element["bremsstrahlung_reaction_IDs_offset"]
    end = start + length
    data[start:end] = value


@njit
def ionization_subshell_binding_energy(index, element, data, value):
    offset = element["ionization_subshell_binding_energy_offset"]
    data[offset + index] = value


@njit
def ionization_subshell_binding_energy_all(element, data, value):
    start = element["ionization_subshell_binding_energy_offset"]
    size = element["ionization_subshell_binding_energy_length"]
    end = start + size
    data[start:end] = value


@njit
def ionization_subshell_binding_energy_last(element, data, value):
    start = element["ionization_subshell_binding_energy_offset"]
    size = element["ionization_subshell_binding_energy_length"]
    end = start + size
    data[end - 1] = value


@njit
def ionization_subshell_binding_energy_chunk(start, length, element, data, value):
    start += element["ionization_subshell_binding_energy_offset"]
    end = start + length
    data[start:end] = value
