# The following is automatically generated by code_factory.py

from numba import njit


@njit
def cell_IDs(index, forced_collisions, data, value):
    offset = forced_collisions["cell_IDs_offset"]
    data[offset + index] = value


@njit
def cell_IDs_all(forced_collisions, data, value):
    start = forced_collisions["cell_IDs_offset"]
    size = forced_collisions["cell_IDs_length"]
    end = start + size
    data[start:end] = value


@njit
def cell_IDs_last(forced_collisions, data, value):
    start = forced_collisions["cell_IDs_offset"]
    size = forced_collisions["cell_IDs_length"]
    end = start + size
    data[end - 1] = value


@njit
def cell_IDs_chunk(start, length, forced_collisions, data, value):
    start += forced_collisions["cell_IDs_offset"]
    end = start + length
    data[start:end] = value
