# The following is automatically generated by code_factory.py

from numba import njit


@njit
def nuclide_IDs(index, native_material, data, value):
    offset = native_material["nuclide_IDs_offset"]
    data[offset + index] = value


@njit
def nuclide_IDs_all(native_material, data, value):
    start = native_material["nuclide_IDs_offset"]
    size = native_material["N_nuclide"]
    end = start + size
    data[start:end] = value


@njit
def nuclide_IDs_last(native_material, data, value):
    start = native_material["nuclide_IDs_offset"]
    size = native_material["N_nuclide"]
    end = start + size
    data[end - 1] = value


@njit
def nuclide_IDs_chunk(start, length, native_material, data, value):
    start += native_material["nuclide_IDs_offset"]
    end = start + length
    data[start:end] = value


@njit
def nuclide_densities(index, native_material, data, value):
    offset = native_material["nuclide_densities_offset"]
    data[offset + index] = value


@njit
def nuclide_densities_all(native_material, data, value):
    start = native_material["nuclide_densities_offset"]
    size = native_material["nuclide_densities_length"]
    end = start + size
    data[start:end] = value


@njit
def nuclide_densities_last(native_material, data, value):
    start = native_material["nuclide_densities_offset"]
    size = native_material["nuclide_densities_length"]
    end = start + size
    data[end - 1] = value


@njit
def nuclide_densities_chunk(start, length, native_material, data, value):
    start += native_material["nuclide_densities_offset"]
    end = start + length
    data[start:end] = value
