# The following is automatically generated by code_factory.py

from numba import njit


@njit
def cdf(index, nbody_distribution, data, value):
    offset = nbody_distribution["cdf_offset"]
    data[offset + index] = value


@njit
def cdf_all(nbody_distribution, data, value):
    start = nbody_distribution["cdf_offset"]
    size = nbody_distribution["cdf_length"]
    end = start + size
    data[start:end] = value


@njit
def cdf_last(nbody_distribution, data, value):
    start = nbody_distribution["cdf_offset"]
    size = nbody_distribution["cdf_length"]
    end = start + size
    data[end - 1] = value


@njit
def cdf_chunk(start, length, nbody_distribution, data, value):
    start += nbody_distribution["cdf_offset"]
    end = start + length
    data[start:end] = value
