# The following is automatically generated by code_factory.py

from numba import njit


@njit
def subshell_x_IDs(index, photon_photoelectric_reaction, data, value):
    offset = photon_photoelectric_reaction["subshell_x_IDs_offset"]
    data[offset + index] = value


@njit
def subshell_x_IDs_all(photon_photoelectric_reaction, data, value):
    start = photon_photoelectric_reaction["subshell_x_IDs_offset"]
    size = photon_photoelectric_reaction["N_subshell_x"]
    end = start + size
    data[start:end] = value


@njit
def subshell_x_IDs_last(photon_photoelectric_reaction, data, value):
    start = photon_photoelectric_reaction["subshell_x_IDs_offset"]
    size = photon_photoelectric_reaction["N_subshell_x"]
    end = start + size
    data[end - 1] = value


@njit
def subshell_x_IDs_chunk(start, length, photon_photoelectric_reaction, data, value):
    start += photon_photoelectric_reaction["subshell_x_IDs_offset"]
    end = start + length
    data[start:end] = value
