# The following is automatically generated by code_factory.py

from numba import njit


@njit
def xs(index, photon_reaction, data, value):
    offset = photon_reaction["xs_offset"]
    data[offset + index] = value


@njit
def xs_all(photon_reaction, data, value):
    start = photon_reaction["xs_offset"]
    size = photon_reaction["xs_length"]
    end = start + size
    data[start:end] = value


@njit
def xs_last(photon_reaction, data, value):
    start = photon_reaction["xs_offset"]
    size = photon_reaction["xs_length"]
    end = start + size
    data[end - 1] = value


@njit
def xs_chunk(start, length, photon_reaction, data, value):
    start += photon_reaction["xs_offset"]
    end = start + length
    data[start:end] = value


@njit
def secondary_product_IDs(index, photon_reaction, data, value):
    offset = photon_reaction["secondary_product_IDs_offset"]
    data[offset + index] = value


@njit
def secondary_product_IDs_all(photon_reaction, data, value):
    start = photon_reaction["secondary_product_IDs_offset"]
    size = photon_reaction["N_secondary_product"]
    end = start + size
    data[start:end] = value


@njit
def secondary_product_IDs_last(photon_reaction, data, value):
    start = photon_reaction["secondary_product_IDs_offset"]
    size = photon_reaction["N_secondary_product"]
    end = start + size
    data[end - 1] = value


@njit
def secondary_product_IDs_chunk(start, length, photon_reaction, data, value):
    start += photon_reaction["secondary_product_IDs_offset"]
    end = start + length
    data[start:end] = value
