# The following is automatically generated by code_factory.py

from numba import njit


@njit
def xs(index, proton_reaction, data, value):
    offset = proton_reaction["xs_offset"]
    data[offset + index] = value


@njit
def xs_all(proton_reaction, data, value):
    start = proton_reaction["xs_offset"]
    size = proton_reaction["xs_length"]
    end = start + size
    data[start:end] = value


@njit
def xs_last(proton_reaction, data, value):
    start = proton_reaction["xs_offset"]
    size = proton_reaction["xs_length"]
    end = start + size
    data[end - 1] = value


@njit
def xs_chunk(start, length, proton_reaction, data, value):
    start += proton_reaction["xs_offset"]
    end = start + length
    data[start:end] = value
