# The following is automatically generated by code_factory.py

from numba import njit


@njit
def spectrum_probability_grid(index, proton_inelastic_scattering_reaction, data, value):
    offset = proton_inelastic_scattering_reaction["spectrum_probability_grid_offset"]
    data[offset + index] = value


@njit
def spectrum_probability_grid_all(proton_inelastic_scattering_reaction, data, value):
    start = proton_inelastic_scattering_reaction["spectrum_probability_grid_offset"]
    size = proton_inelastic_scattering_reaction["spectrum_probability_grid_length"]
    end = start + size
    data[start:end] = value


@njit
def spectrum_probability_grid_last(proton_inelastic_scattering_reaction, data, value):
    start = proton_inelastic_scattering_reaction["spectrum_probability_grid_offset"]
    size = proton_inelastic_scattering_reaction["spectrum_probability_grid_length"]
    end = start + size
    data[end - 1] = value


@njit
def spectrum_probability_grid_chunk(start, length, proton_inelastic_scattering_reaction, data, value):
    start += proton_inelastic_scattering_reaction["spectrum_probability_grid_offset"]
    end = start + length
    data[start:end] = value


@njit
def spectrum_probability_vector(index_1, proton_inelastic_scattering_reaction, data, value):
    offset = proton_inelastic_scattering_reaction["spectrum_probability_offset"]
    stride = proton_inelastic_scattering_reaction["N_spectrum"]
    start = offset + index_1 * stride
    end = start + stride
    data[start:end] - value


@njit
def spectrum_probability(index_1, index_2, proton_inelastic_scattering_reaction, data, value):
    offset = proton_inelastic_scattering_reaction["spectrum_probability_offset"]
    stride = proton_inelastic_scattering_reaction["N_spectrum"]
    data[offset + index_1 * stride + index_2] = value


@njit
def spectrum_probability_chunk(start, length, proton_inelastic_scattering_reaction, data, value):
    start += proton_inelastic_scattering_reaction["spectrum_probability_offset"]
    end = start + length
    data[start:end] = value


@njit
def energy_spectrum_IDs(index, proton_inelastic_scattering_reaction, data, value):
    offset = proton_inelastic_scattering_reaction["energy_spectrum_IDs_offset"]
    data[offset + index] = value


@njit
def energy_spectrum_IDs_all(proton_inelastic_scattering_reaction, data, value):
    start = proton_inelastic_scattering_reaction["energy_spectrum_IDs_offset"]
    size = proton_inelastic_scattering_reaction["N_energy_spectrum"]
    end = start + size
    data[start:end] = value


@njit
def energy_spectrum_IDs_last(proton_inelastic_scattering_reaction, data, value):
    start = proton_inelastic_scattering_reaction["energy_spectrum_IDs_offset"]
    size = proton_inelastic_scattering_reaction["N_energy_spectrum"]
    end = start + size
    data[end - 1] = value


@njit
def energy_spectrum_IDs_chunk(start, length, proton_inelastic_scattering_reaction, data, value):
    start += proton_inelastic_scattering_reaction["energy_spectrum_IDs_offset"]
    end = start + length
    data[start:end] = value
