# The following is automatically generated by code_factory.py

from numba import njit


@njit
def census_time(index, settings, data, value):
    offset = settings["census_time_offset"]
    data[offset + index] = value


@njit
def census_time_all(settings, data, value):
    start = settings["census_time_offset"]
    size = settings["census_time_length"]
    end = start + size
    data[start:end] = value


@njit
def census_time_last(settings, data, value):
    start = settings["census_time_offset"]
    size = settings["census_time_length"]
    end = start + size
    data[end - 1] = value


@njit
def census_time_chunk(start, length, settings, data, value):
    start += settings["census_time_offset"]
    end = start + length
    data[start:end] = value
