# The following is automatically generated by code_factory.py

from numba import njit


@njit
def x(index, structured_mesh, data, value):
    offset = structured_mesh["x_offset"]
    data[offset + index] = value


@njit
def x_all(structured_mesh, data, value):
    start = structured_mesh["x_offset"]
    size = structured_mesh["x_length"]
    end = start + size
    data[start:end] = value


@njit
def x_last(structured_mesh, data, value):
    start = structured_mesh["x_offset"]
    size = structured_mesh["x_length"]
    end = start + size
    data[end - 1] = value


@njit
def x_chunk(start, length, structured_mesh, data, value):
    start += structured_mesh["x_offset"]
    end = start + length
    data[start:end] = value


@njit
def y(index, structured_mesh, data, value):
    offset = structured_mesh["y_offset"]
    data[offset + index] = value


@njit
def y_all(structured_mesh, data, value):
    start = structured_mesh["y_offset"]
    size = structured_mesh["y_length"]
    end = start + size
    data[start:end] = value


@njit
def y_last(structured_mesh, data, value):
    start = structured_mesh["y_offset"]
    size = structured_mesh["y_length"]
    end = start + size
    data[end - 1] = value


@njit
def y_chunk(start, length, structured_mesh, data, value):
    start += structured_mesh["y_offset"]
    end = start + length
    data[start:end] = value


@njit
def z(index, structured_mesh, data, value):
    offset = structured_mesh["z_offset"]
    data[offset + index] = value


@njit
def z_all(structured_mesh, data, value):
    start = structured_mesh["z_offset"]
    size = structured_mesh["z_length"]
    end = start + size
    data[start:end] = value


@njit
def z_last(structured_mesh, data, value):
    start = structured_mesh["z_offset"]
    size = structured_mesh["z_length"]
    end = start + size
    data[end - 1] = value


@njit
def z_chunk(start, length, structured_mesh, data, value):
    start += structured_mesh["z_offset"]
    end = start + length
    data[start:end] = value
