# The following is automatically generated by code_factory.py

from numba import njit


@njit
def x(index, table_data, data, value):
    offset = table_data["x_offset"]
    data[offset + index] = value


@njit
def x_all(table_data, data, value):
    start = table_data["x_offset"]
    size = table_data["x_length"]
    end = start + size
    data[start:end] = value


@njit
def x_last(table_data, data, value):
    start = table_data["x_offset"]
    size = table_data["x_length"]
    end = start + size
    data[end - 1] = value


@njit
def x_chunk(start, length, table_data, data, value):
    start += table_data["x_offset"]
    end = start + length
    data[start:end] = value


@njit
def y(index, table_data, data, value):
    offset = table_data["y_offset"]
    data[offset + index] = value


@njit
def y_all(table_data, data, value):
    start = table_data["y_offset"]
    size = table_data["y_length"]
    end = start + size
    data[start:end] = value


@njit
def y_last(table_data, data, value):
    start = table_data["y_offset"]
    size = table_data["y_length"]
    end = start + size
    data[end - 1] = value


@njit
def y_chunk(start, length, table_data, data, value):
    start += table_data["y_offset"]
    end = start + length
    data[start:end] = value
