# The following is automatically generated by code_factory.py

from numba import njit


@njit
def value(index, tabulated_distribution, data, value):
    offset = tabulated_distribution["value_offset"]
    data[offset + index] = value


@njit
def value_all(tabulated_distribution, data, value):
    start = tabulated_distribution["value_offset"]
    size = tabulated_distribution["value_length"]
    end = start + size
    data[start:end] = value


@njit
def value_last(tabulated_distribution, data, value):
    start = tabulated_distribution["value_offset"]
    size = tabulated_distribution["value_length"]
    end = start + size
    data[end - 1] = value


@njit
def value_chunk(start, length, tabulated_distribution, data, value):
    start += tabulated_distribution["value_offset"]
    end = start + length
    data[start:end] = value


@njit
def pdf(index, tabulated_distribution, data, value):
    offset = tabulated_distribution["pdf_offset"]
    data[offset + index] = value


@njit
def pdf_all(tabulated_distribution, data, value):
    start = tabulated_distribution["pdf_offset"]
    size = tabulated_distribution["pdf_length"]
    end = start + size
    data[start:end] = value


@njit
def pdf_last(tabulated_distribution, data, value):
    start = tabulated_distribution["pdf_offset"]
    size = tabulated_distribution["pdf_length"]
    end = start + size
    data[end - 1] = value


@njit
def pdf_chunk(start, length, tabulated_distribution, data, value):
    start += tabulated_distribution["pdf_offset"]
    end = start + length
    data[start:end] = value


@njit
def cdf(index, tabulated_distribution, data, value):
    offset = tabulated_distribution["cdf_offset"]
    data[offset + index] = value


@njit
def cdf_all(tabulated_distribution, data, value):
    start = tabulated_distribution["cdf_offset"]
    size = tabulated_distribution["cdf_length"]
    end = start + size
    data[start:end] = value


@njit
def cdf_last(tabulated_distribution, data, value):
    start = tabulated_distribution["cdf_offset"]
    size = tabulated_distribution["cdf_length"]
    end = start + size
    data[end - 1] = value


@njit
def cdf_chunk(start, length, tabulated_distribution, data, value):
    start += tabulated_distribution["cdf_offset"]
    end = start + length
    data[start:end] = value
