# The following is automatically generated by code_factory.py

from numba import njit


@njit
def weight_window_types(index, technique, data, value):
    offset = technique["weight_window_types_offset"]
    data[offset + index] = value


@njit
def weight_window_types_all(technique, data, value):
    start = technique["weight_window_types_offset"]
    size = technique["weight_window_types_length"]
    end = start + size
    data[start:end] = value


@njit
def weight_window_types_last(technique, data, value):
    start = technique["weight_window_types_offset"]
    size = technique["weight_window_types_length"]
    end = start + size
    data[end - 1] = value


@njit
def weight_window_types_chunk(start, length, technique, data, value):
    start += technique["weight_window_types_offset"]
    end = start + length
    data[start:end] = value


@njit
def weight_window_IDs(index, technique, data, value):
    offset = technique["weight_window_IDs_offset"]
    data[offset + index] = value


@njit
def weight_window_IDs_all(technique, data, value):
    start = technique["weight_window_IDs_offset"]
    size = technique["N_weight_window"]
    end = start + size
    data[start:end] = value


@njit
def weight_window_IDs_last(technique, data, value):
    start = technique["weight_window_IDs_offset"]
    size = technique["N_weight_window"]
    end = start + size
    data[end - 1] = value


@njit
def weight_window_IDs_chunk(start, length, technique, data, value):
    start += technique["weight_window_IDs_offset"]
    end = start + length
    data[start:end] = value
