# The following is automatically generated by code_factory.py

from numba import njit


@njit
def weight_windows(index, weight_windows, data, value):
    offset = weight_windows["weight_windows_offset"]
    data[offset + index] = value


@njit
def weight_windows_all(weight_windows, data, value):
    start = weight_windows["weight_windows_offset"]
    size = weight_windows["weight_windows_length"]
    end = start + size
    data[start:end] = value


@njit
def weight_windows_last(weight_windows, data, value):
    start = weight_windows["weight_windows_offset"]
    size = weight_windows["weight_windows_length"]
    end = start + size
    data[end - 1] = value


@njit
def weight_windows_chunk(start, length, weight_windows, data, value):
    start += weight_windows["weight_windows_offset"]
    end = start + length
    data[start:end] = value
