name: Mark stale issues

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-stale: 90
          days-before-issue-close: -1
          stale-issue-label: "status: stale"
          stale-issue-message: >
            This issue has had no activity in the past 90 days and has been marked as stale.
            If this issue is still relevant, please leave a comment with any updates so we know it still needs attention.
            Otherwise, maintainers may close this issue in the future. Thank you for your contribution!

          # Do not stale PRs
          days-before-pr-stale: -1
          days-before-pr-close: -1
